name: Commitlint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm install --no-save @commitlint/{config-conventional,cli}
      - run: npx commitlint --from=origin/main --to=HEAD --verbose || echo "Aviso: commitlint falhou. Ajuste as mensagens de commit."
