name: Commitlint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm install --no-save @commitlint/config-conventional @commitlint/cli
      - name: Commit message lint
        shell: bash
        run: |
          npx commitlint --from="${{ github.base_ref }}" --to=HEAD --verbose || echo "Aviso: commitlint falhou. Ajuste as mensagens de commit."
